export class Customer {

  constructor(public firstName = '',
    public lastName = '',
    public email = '',
    public sendCatalog = false,
    public addressType = 'home',
    public street1?: string,
    public street2?: string,
    public city?: string,
    public state = '',
    public phase1 = false,
    public phase2 = false,
    public phase3 = false,
    public phase4 = false,
    public phase5 = false,
    public p1_addon_1 = false,
    public p1_addon_2 = false,
    public p1_addon_3 = false,
    public p1_addon_4 = false,
    public p1_addon_5 = false,
    public p2_addon_1 = false,
    public p2_addon_2 = false,
    public p2_addon_3 = false,
    public p2_addon_4 = false,
    public p2_addon_5 = false,
    public p2_addon_6 = false,
    public p2_addon_7 = false,
    public p3_addon_1 = false,
    public p3_addon_2 = false,
    public p3_addon_3 = false,
    public p4_addon_1 = false,
    public p4_addon_2 = false,
    public p4_addon_3 = false,
    public p4_addon_4 = false,
    public p4_addon_5 = false,
    public p5_addon_1 = false,
    public p5_addon_2 = false,
    public p5_addon_3 = false,
    public p5_addon_4 = false,
    public p5_addon_5 = false,
    public p5_addon_6 = false,
    public p5_addon_7 = false,
    public p5_addon_8 = false,
    public p5_addon_9 = false,
    public p5_addon_10 = false,
    public p5_addon_11 = false,
    public p5_addon_12 = false,
    public p5_addon_13 = false,
    public p6_addon_1 = false,
    public p6_addon_2 = false,
    public p6_addon_3 = false,
    public p6_addon_4 = false,
    public p6_addon_5 = false,
    public p6_addon_6 = false,
    public p6_addon_7 = false,
    public card1Expanded = false,
    public card2Expanded = false,
    public card3Expanded = false,
    public card4Expanded = false,
    public card5Expanded = false,
    public card6Expanded = false,
    public total = 0,
    public company = '',

    public zip?: string) { }
    
}
